# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51c24ed46b50261ce59e7bc37e7d7e60c0efdb0831f7da05edf6e2c837401fefae5a10fd21bf102e601cdc78a57d90995d7b7727ff9a90e05570821d86de9e4b

test:
  secret_key_base: 1f9dd2b2f97368c622803d43c16bc5ed279b56b610ebd21848b11234302bda1185bc3f68339e061823a7146a9d5bed98c32fa6a57e3c7295ca84a0e806d965f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
